[app_servers]
devops-all-in-one ansible_host=107.21.156.231 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem

[monitor_servers]
devops-all-in-one ansible_host=107.21.156.231 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem
